# Generated by Django 4.2.4 on 2023-09-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HMSTRACKER", "0002_alter_hospitaldata_nhif_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="hospitaldata", name="IDno",),
        migrations.RemoveField(model_name="hospitaldata", name="NHIF",),
        migrations.RemoveField(model_name="hospitaldata", name="birthCertificate",),
        migrations.RemoveField(model_name="hospitaldata", name="county",),
        migrations.RemoveField(model_name="hospitaldata", name="firstContact",),
        migrations.RemoveField(model_name="hospitaldata", name="firstName",),
        migrations.RemoveField(model_name="hospitaldata", name="lastName",),
        migrations.RemoveField(model_name="hospitaldata", name="location",),
        migrations.RemoveField(model_name="hospitaldata", name="middleName",),
        migrations.RemoveField(model_name="hospitaldata", name="residence",),
        migrations.RemoveField(model_name="hospitaldata", name="secondContact",),
        migrations.RemoveField(model_name="hospitaldata", name="village",),
    ]
