# Generated by Django 4.2.4 on 2023-09-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "HMSTRACKER",
            "0003_remove_hospitaldata_idno_remove_hospitaldata_nhif_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="preliminaryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField()),
                ("bloodPressure", models.IntegerField()),
                ("hiv", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(name="HospitalData",),
    ]
