# Generated by Django 4.2.4 on 2023-10-01 08:25

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HMSTRACKER", "0004_preliminarydata_delete_hospitaldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paymentMode", models.CharField(max_length=100)),
                (
                    "TotalCost",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("transactionID", models.CharField(max_length=15)),
                (
                    "paidAmount",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("paymentDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration", models.IntegerField(default=100)),
                ("consultation", models.IntegerField(default=500)),
                ("lab", models.IntegerField(default=5000)),
                ("pharmacy", models.IntegerField(default=8000)),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consultationRoom", models.IntegerField()),
                ("recomendation", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Prescrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availableMedicine", models.CharField(max_length=300)),
                ("outOfStock", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientId", models.IntegerField()),
                ("patientName", models.CharField(max_length=50)),
                ("testResults", models.TextField()),
                (
                    "physcicianRoom",
                    models.ForeignKey(
                        on_delete=builtins.callable, to="HMSTRACKER.consultation"
                    ),
                ),
            ],
        ),
    ]
