# Generated by Django 4.2.4 on 2023-10-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HMSTRACKER", "0005_accounts_charges_consultation_prescrition_laboratory"),
    ]

    operations = [
        migrations.RemoveField(model_name="charges", name="consultation",),
        migrations.RemoveField(model_name="charges", name="lab",),
        migrations.RemoveField(model_name="charges", name="pharmacy",),
        migrations.RemoveField(model_name="charges", name="registration",),
    ]
