# Generated by Django 4.2.4 on 2023-10-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HMSTRACKER", "0006_remove_charges_consultation_remove_charges_lab_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Charges",),
    ]
