# Generated by Django 4.2.4 on 2023-10-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HMSTRACKER", "0007_delete_charges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescrition",
            name="availableMedicine",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="prescrition", name="outOfStock", field=models.TextField(),
        ),
    ]
