# Generated by Django 4.2.4 on 2023-10-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "HMSTRACKER",
            "0010_rename_prescriptions_medicinerecommendations_prescription",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="consultation", name="consultationRoom",),
    ]
